### PR TITLE
add icon

### LINKED ISSUE #99: add logo to page
Since we have a nice favicon setup now, why don't include it to the page itself for a better branding?

Could look like this:
logo

### PR DESCRIPTION
**Pull request by tooomm**
fixes #99

I couldn't properly test it locally.

@blakdeth: was there a special reason you used base64 coding?

### CODE REVIEW

**Comment by NilsEnevoldsen** [comment]
I would add about 1em of margin-right to the logo.

**Comment by tooomm** [comment]
@NilsEnevoldsen The icon file itself has some whitespace included

**Comment by NilsEnevoldsen** [comment]
@tooomm I think it looks better with added margin, but if you prefer without then that's fine.

screen shot 2018-09-16 at 10 00 38 am
screen shot 2018-09-16 at 10 01 07 am

**Comment by NilsEnevoldsen** [comment]
I don't know how to add to somebody else's PR.

**Comment by tooomm** [comment]
As long as you have some rights in this repo, you can add to my branch in my fork where I created this pr from directly.
(There is a check mark setting for the pr creator in the right column to allow this)

**Comment by NilsEnevoldsen** [comment]
I do not appear to have write access to this repo.

I might do it this way.

In index.html:
```html
<img id="site-icon" src="icon-original.svg">
```

In style.css:
```css
#site-icon {
  float: left;
  height: 5em;
  margin: 0em 0.5em;
}
```

**Comment by tooomm** [comment]
Thanks @NilsEnevoldsen! I added the second margin to the left as well.

**Comment by NilsEnevoldsen** [comment]
@tooomm When margin has two values, the first is top & bottom and the second is left & right.

**Comment by glacials** [comment]
Thanks for the contribution!

**Comment by tooomm** [comment]
Thanks for your help and input @NilsEnevoldsen 👍

**Pull request merged**
