### PR TITLE
Monumetric ads and ads.txt added.

### PR DESCRIPTION
**Pull request by shirbhatesushil**
Monumetric ads and ads.txt added.

### CODE REVIEW

**Comment by glacials** [comment]
For context for others: I'm looking at changing ad providers and Monumetric is one option. They insisted that they alone can make the changes, so here we are. For reference AdSense brings in about $16 per month.

@shirbhatesushil: I see over 100 new requests being made in the background, and no ads. Both of these seem like issues. Any idea what's going on?

**Comment by shirbhatesushil** [comment]
@glacials ,
Ads will show after ads.txt scan and it will take time, so please marge our code and make it live.
I made only three commit.

**Comment by glacials** [comment]
@shirbhatesushil Any comment on the 100+ new requests being made in the background? Are those necessary?

**Comment by shirbhatesushil** [comment]
@glacials ,
I not found 100+ new request made by me, sorry I'm new in Git.
I only commit following three commit and only this is pull request made by me
https://github.com/glacials/whatsinstandard/pull/147/commits/13368365f93b55b6e971f7a3e5fdfab61d2a6289
https://github.com/glacials/whatsinstandard/pull/147/commits/fda7b95c397c0c94d83747565100ffbd35d0bcab
https://github.com/glacials/whatsinstandard/pull/147/commits/bb7664570f8618dce2b6cfd0b03676c2eadb8fe7

**Comment by glacials** [comment]
@shirbhatesushil: You can see what I mean by opening the Chrome inspector's network tab:

From a fresh load, ~10s after pageload on `master`, 67 requests made:

Screen Shot 2019-10-16 at 10 34 52

From a fresh load, ~10s after pageload on this branch, 252 requests made:

Screen Shot 2019-10-16 at 10 34 22

**Comment by shirbhatesushil** [comment]
@glacials 
Our team checking, I will provide you updates very soon.

**Comment by shirbhatesushil** [comment]
@glacials ,
Our ads not showing on site, so our team can't check it.
Can you please marge this request so we can check it?

**Comment by glacials** [comment]
@shirbhatesushil: You can check it locally by running

```sh
npm install
npm start
```
Sorry but I'm not going to merge this while this issue is present. I also need some sort of ability to preview what the ads look like before merging. I'm closing this issue, but please reopen if you can address these two concerns.

**Pull request closed without merging**
