### PR TITLE
icon fonts and miscellaneous stuff

### PR DESCRIPTION
**Pull request by pixelwhiskey**
Hey @glacials,

Not sure what you think about this but I threw this together in a few and thought I would just submit a PR so you'd have a better idea.

1. Converted all your set icons to the Keyrune icon font. More here: http://andrewgioia.github.io/Keyrune/
2. Deleted all your SVG set icons. Less file requests on load.
3. Moved your dropped sets toggle JS after the tipsy call to reduce JS file request.  If you get more javascript I would probably put it in a standalone JS file.

Regards,
Reece

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The only one I'm not 100% sold on is (3), but I understand the logic behind it. (just not sure the site is big or weighty enough to warrant moving JS inline to remove a single request)
Otherwise, looks great. :shipit:

**Comment by pixelwhiskey** [comment]
@Nightfirecat yep, I'm cool with putting that back in. just went ahead and made the change but can undo if thats the consensus.

**Comment by glacials** [comment]
I'm surprised the font is only 55K -- was gonna say it's not worth increasing number of bytes drastically to save ~7 requests, but that's actually about the same size as the SVGs. Do you know why this is? I don't know much about this area, so I want to make sure I'm not missing something.

If this is a magic bullet though, that's awesome. Assuming it is, I imagine this will break some tests; can you fix them or remove them if they're no longer relevant?

And yeah I agree with @Nightfirecat that saving one request here or there isn't worth sacrificing organization. I'd really only start to be concerned if we're talking about tens of requests.

**Comment by pixelwhiskey** [comment]
@glacials - ill update any failing tests and revert the inline js

**Comment by pixelwhiskey** [comment]
@glacials @Nightfirecat 
1. replaced the separate js file `toggleRecentlyDropped.js`
2. updated `sets.json` and replaced/updated some of the unit tests - they all pass now.  let me know if there was something else you had in mind for this.

**Comment by Nightfirecat** [comment]
Looking better. The commit message needs fixing (the JS isn't inlined anymore), and the JS file looks like it had its spaces changed from 2->4, could that be changed back? Otherwise, looks fine at a glance.

**Comment by glacials** [comment]
Ah, this makes me realize that this is a breaking API change. The API docs guarantee that `symbol` contains a URL to the set image. So we can either undelete the set images for now or use Gatherer image URLs (see README for example), I'll leave it up to you.

Can you remove the changes that are unrelated this branch, like the CSS selector changes and such? I'm happy to discuss code organization in its own PR, but piggybacking stuff onto other stuff just makes both stuffs harder to review and talk about.

[1]: http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=DTK&size=large&rarity=C

**Comment by pixelwhiskey** [comment]
@Nightfirecat @glacials - ok paired it down

This just contains the icon font change for the front-end.

**Comment by Nightfirecat** [comment]
:+1: :shipit:

**Comment by glacials** [comment]
Thanks @pixelwhiskey!!!

**Pull request merged**
