### PR TITLE
Add hearthstone to whatsinstandard

### PR DESCRIPTION
**Pull request by jpcostallos**
Being that Hearthstone announced they would also be naming their format rotation "standard" I saw your website and thought it easily lent itself to also support hearthstone. Many Magic players I know also play hearthstone, so it could be a nice fit. 

A lot of the copy i used describing hearthstone standard format came from http://hearthstone.gamepedia.com/Standard_format#Year_of_the_Kraken & http://us.battle.net/hearthstone/en/blog/19995505/a-new-way-to-play-2-2-2016

This copy can be edited obviously, I just wanted to present the idea with potential information to be included.

I did not add to the API, as that can be something that is done if/when you continue with the idea of adding hearthstone to the site. I would be happy to add that if we move forward.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
From a UX standpoint, I'd feel better if these were compartmentalized into different pages; I wouldn't feel great about seeing both MtG and Hearthstone rotations listed on the same page. Just my 2c.

**Comment by jpcostallos** [comment]
@Nightfirecat I understand your concern. I tried to implement it so that you could easily see the differences between the 2 games (see screenshot below). More UX features could be added to emphasize the differences or like you said making them separate pages all together. I think the cool connection here though is that both Magic & Hearthstone now have "standard" formats and the website domain caters to both of those games.

screen shot 2016-04-12 at 1 09 40 pm

**Comment by glacials** [comment]
Hi, thanks for your PR!

I agree that these resources do not belong on the same page. WIS is meant to answer a very specific question very quickly, so minimizing visual clutter is high priority. And although the player bases overlap, the use cases don't -- people ask "What's in MTG Standard?" and "What's in Hearthstone Standard?", but I don't imagine they ever ask both at the same time. So 50% of the page will just be clutter that the user wasn't looking for.

On the more general level of including Hearthstone info, @bdzs has actually already forked this project to [bdzs/whatsinstandard][1], which gives [standardhearth.com][2]. I probably wouldn't want to duplicate work, so maybe we can crosslink the two sites or something.

[1]: https://github.com/bdzs/whatsinstandard
[2]: http://standardhearth.com/

**Comment by jpcostallos** [comment]
@glacials AH, i never saw that fork. Ok then. I suppose that accomplishes the same goal then. I think you're right about it possibly confusing players who don't participate in both HS AND MTG, even if it is neat that they both share the same terminology of "standard" when referencing playable formats. Crosslinking the sites sounds like a great idea, even if it's just a small non-distracting link towards the bottom of the page or something of the sort.

Thanks for the input, fun project!

**Comment by Nightfirecat** [comment]
I agree with cross-linking projects; opened #23 for it.

**Pull request closed without merging**
