### PR TITLE
Change to the new Rotation 2027

### PR DESCRIPTION
**Pull request by lieyanqzu**
- Modified the timeline based on the new rotation rules
https://magic.wizards.com/en/news/announcements/aligning-the-universes-making-all-our-sets-legal-in-all-our-formats
- Update keyrune version
- Show one more rotation round (temporary I think)

PS: Maybe the rotation date can be clearer now, such as when the first set of 2027 releases?

### CODE REVIEW

**Comment by riQQ** [comment]
> Note that this means Bloomburrow and Duskmourn: House of Horror will both be legal for slightly shorter than originally anticipated.

They should have rough exit date Q1 2028, not Q1 2027, i.e. they are Standard legal minimum full 3 years.

**Comment by lieyanqzu** [comment]
> > Note that this means Bloomburrow and Duskmourn: House of Horror will both be legal for slightly shorter than originally anticipated.
> 
> They should have rough exit date Q1 2028, not Q1 2027, i.e. they are Standard legal minimum full 3 years.

I don't think so, the article said blb and dsk will be shorter than normal three year.
And mtgwiki also shows they will exit in Q1 2027. https://mtg.fandom.com/wiki/Standard#Set_legality

**Comment by riQQ** [comment]
Oh, sorry, you're right. I totally misread the passage I quoted.

**Review by glacials — APPROVED** [review]
Thanks for going through and updating these! Yeah the descriptive text could probably benefit from an update as well.

**Pull request merged**
