### PR TITLE
Add crosslink to Hearthstone What's in Standard

### PR DESCRIPTION
**Pull request by Nightfirecat**
Uses same formatting/style as bdzs/whatsinstandard#1.

Closes glacials/whatsinstandard#23

### CODE REVIEW

**Comment by glacials** [comment]
I'd like this flatter, like

screenshot 2016-04-16 01 38 26
screenshot 2016-04-16 01 38 01

But before we change any code: @bdzs, any preferences for how this looks? Consistency would be great if we are both ok with the same design.

**Comment by bdzs** [comment]
Yeah that looks good! If you make it for your site I'll just copy then, if that's fine :D

**Comment by Nightfirecat** [comment]
Looks good, merged your change into this PR.

**Comment by Nightfirecat** [comment]
I'll squash the merge commit away if you want it gone, btw.

**Comment by glacials** [comment]
Nah it's always good.

**Comment by glacials** [comment]
ty :3

**Pull request merged**
