### PR TITLE
Dynamicupdate test

### PR DESCRIPTION
**Pull request by inuyasha82**
There are for sure few things that i still need to fix (i.e. some of the variable names in app.js) 

I also updated the folder bower-components (it makes the pull request a little bit harder to read).

### CODE REVIEW

**Comment by inuyasha82** [comment]
I fixed the variable name, and removed the time from rotation date.

**Comment by glacials** [comment]
Sorry it's taking me so long to look at this, should be able to get to it this weekend!

**Comment by inuyasha82** [comment]
No rush! Don't worry!

Il 24 Giu 2017 1:11 AM, "Ben Carlsson" <notifications@github.com> ha
scritto:

Sorry it's taking me so long to look at this, should be able to get to it
this weekend!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glacials/whatsinstandard/pull/56#issuecomment-310792195>,
or mute the thread

**Comment by inuyasha82** [comment]
Hi @glacials 
i updated the code (and i hope i merged correctly, please check), so now the item that has to be released are greyed as requested.
And also fixed the code for the tile on a block when it has a set not released yet.

I noticed that you added a new class called: list-group-item--upcoming
Is normal the double -? Or just a typo? if you want i can fix it in this pull request.

**Comment by glacials** [comment]
Looks good! The double hyphen is on purpose, and was added in #26. See here for more info: https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

Since I changed the base branch for the repository from `gh-pages` to `master`, you'll need to remake this pull request since this one still wants to merge into `gh-pages`:

screenshot 2017-07-05 12 02 45

Once you do that, I'm good to merge!

**Comment by inuyasha82** [comment]
Opened new Pull Request #59 against master

**Pull request closed without merging**
